{
  "hash": "65a04de0b62de8a457bf9b8287089b41",
  "result": {
    "markdown": "---\ntitle: \"Regression and Statistical Inference\"\nauthor: \"Lucas Puebla\"\n---\n\n# Assignment 1\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-1_6b8ecc57150d88ee09798b0a2e29ebf0'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n#> ✔ dplyr     1.1.4     ✔ readr     2.1.4\n#> ✔ forcats   1.0.0     ✔ stringr   1.5.0\n#> ✔ ggplot2   3.4.4     ✔ tibble    3.2.1\n#> ✔ lubridate 1.9.3     ✔ tidyr     1.3.0\n#> ✔ purrr     1.0.2     \n#> ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n#> ✖ dplyr::filter() masks stats::filter()\n#> ✖ dplyr::lag()    masks stats::lag()\n#> ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggthemr)\nlibrary(ggplot2)\nggthemr(\"fresh\") \n\ndf <- readRDS(\"~/GitHub/cdsba-lucaspuebla93/Causal_Data_Science_Data/car_prices.rds\")\n# View(df)\n\n# Check the dimensions of the dataframe\ndimensions <- dim(df) # Retrieve the dimensions (rows and columns) of the dataframe\n\n# Print the number of rows and columns\ncat(\"Number of rows:\", dimensions[1], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> Number of rows: 181\n```\n:::\n\n```{.r .cell-code}\ncat(\"Number of columns:\", dimensions[2], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> Number of columns: 22\n```\n:::\n:::\n\n\n\n\n# Assignment 2\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-2_698b762b9ddbfabfb6dc502e05673454'}\n\n```{.r .cell-code}\nsummary(df) # Gives summary statistics for numerical columns in the dataframe\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>   aspiration         doornumber          carbody           drivewheel       \n#>  Length:181         Length:181         Length:181         Length:181        \n#>  Class :character   Class :character   Class :character   Class :character  \n#>  Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n#>                                                                             \n#>                                                                             \n#>                                                                             \n#>  enginelocation       wheelbase        carlength        carwidth    \n#>  Length:181         Min.   : 86.60   Min.   :141.1   Min.   :60.30  \n#>  Class :character   1st Qu.: 94.50   1st Qu.:166.3   1st Qu.:64.00  \n#>  Mode  :character   Median : 96.50   Median :173.0   Median :65.40  \n#>                     Mean   : 98.21   Mean   :173.3   Mean   :65.74  \n#>                     3rd Qu.:100.40   3rd Qu.:180.2   3rd Qu.:66.50  \n#>                     Max.   :120.90   Max.   :208.1   Max.   :72.30  \n#>    carheight       curbweight    enginetype        cylindernumber    \n#>  Min.   :47.80   Min.   :1488   Length:181         Length:181        \n#>  1st Qu.:52.00   1st Qu.:2122   Class :character   Class :character  \n#>  Median :53.70   Median :2410   Mode  :character   Mode  :character  \n#>  Mean   :53.58   Mean   :2521                                        \n#>  3rd Qu.:55.50   3rd Qu.:2910                                        \n#>  Max.   :59.80   Max.   :4066                                        \n#>    enginesize     fuelsystem          boreratio         stroke    \n#>  Min.   : 61.0   Length:181         Min.   :2.540   Min.   :2.07  \n#>  1st Qu.: 98.0   Class :character   1st Qu.:3.150   1st Qu.:3.08  \n#>  Median :120.0   Mode  :character   Median :3.310   Median :3.23  \n#>  Mean   :127.1                      Mean   :3.325   Mean   :3.23  \n#>  3rd Qu.:141.0                      3rd Qu.:3.590   3rd Qu.:3.40  \n#>  Max.   :326.0                      Max.   :3.940   Max.   :4.17  \n#>  compressionratio   horsepower       peakrpm        citympg     \n#>  Min.   : 7.000   Min.   : 48.0   Min.   :4200   Min.   :13.00  \n#>  1st Qu.: 8.500   1st Qu.: 70.0   1st Qu.:4800   1st Qu.:19.00  \n#>  Median : 9.000   Median : 95.0   Median :5200   Median :24.00  \n#>  Mean   : 8.848   Mean   :106.2   Mean   :5182   Mean   :24.85  \n#>  3rd Qu.: 9.400   3rd Qu.:116.0   3rd Qu.:5500   3rd Qu.:30.00  \n#>  Max.   :11.500   Max.   :288.0   Max.   :6600   Max.   :49.00  \n#>    highwaympg        price      \n#>  Min.   :16.00   Min.   : 5118  \n#>  1st Qu.:25.00   1st Qu.: 7609  \n#>  Median :30.00   Median : 9980  \n#>  Mean   :30.48   Mean   :12999  \n#>  3rd Qu.:34.00   3rd Qu.:16430  \n#>  Max.   :54.00   Max.   :45400\n```\n:::\n\n```{.r .cell-code}\nstr(df) # Shows the structure of the dataframe, including data types\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> Classes 'tbl_df', 'tbl' and 'data.frame':\t181 obs. of  22 variables:\n#>  $ aspiration      : chr  \"std\" \"std\" \"std\" \"std\" ...\n#>  $ doornumber      : chr  \"two\" \"two\" \"two\" \"four\" ...\n#>  $ carbody         : chr  \"convertible\" \"convertible\" \"hatchback\" \"sedan\" ...\n#>  $ drivewheel      : chr  \"rwd\" \"rwd\" \"rwd\" \"fwd\" ...\n#>  $ enginelocation  : chr  \"front\" \"front\" \"front\" \"front\" ...\n#>  $ wheelbase       : num  88.6 88.6 94.5 99.8 99.4 ...\n#>  $ carlength       : num  169 169 171 177 177 ...\n#>  $ carwidth        : num  64.1 64.1 65.5 66.2 66.4 66.3 71.4 71.4 71.4 67.9 ...\n#>  $ carheight       : num  48.8 48.8 52.4 54.3 54.3 53.1 55.7 55.7 55.9 52 ...\n#>  $ curbweight      : num  2548 2548 2823 2337 2824 ...\n#>  $ enginetype      : chr  \"dohc\" \"dohc\" \"ohcv\" \"ohc\" ...\n#>  $ cylindernumber  : chr  \"four\" \"four\" \"six\" \"four\" ...\n#>  $ enginesize      : num  130 130 152 109 136 136 136 136 131 131 ...\n#>  $ fuelsystem      : chr  \"mpfi\" \"mpfi\" \"mpfi\" \"mpfi\" ...\n#>  $ boreratio       : num  3.47 3.47 2.68 3.19 3.19 3.19 3.19 3.19 3.13 3.13 ...\n#>  $ stroke          : num  2.68 2.68 3.47 3.4 3.4 3.4 3.4 3.4 3.4 3.4 ...\n#>  $ compressionratio: num  9 9 9 10 8 8.5 8.5 8.5 8.3 7 ...\n#>  $ horsepower      : num  111 111 154 102 115 110 110 110 140 160 ...\n#>  $ peakrpm         : num  5000 5000 5000 5500 5500 5500 5500 5500 5500 5500 ...\n#>  $ citympg         : num  21 21 19 24 18 19 19 19 17 16 ...\n#>  $ highwaympg      : num  27 27 26 30 22 25 25 25 20 22 ...\n#>  $ price           : num  13495 16500 16500 13950 17450 ...\n```\n:::\n:::\n\nThe dataframe contains columns with numbers and strings. The variables with strings in their columns are considered discrete, while the numbers are continuous.\n\n\n\n# Assignment 3\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-3_2b62add22f593cfa9fb7082ae3bc0768'}\n\n```{.r .cell-code}\n# Select only numeric columns from the dataframe\nnumeric_df <- df[sapply(df, is.numeric)]\n\n# Calculate the correlation matrix for numeric columns\ncorrelation_matrix <- cor(numeric_df)\n\n# Find correlations with the 'price' variable\nprice_correlations <- correlation_matrix['price', ]\nprice_correlations <- price_correlations[!names(price_correlations) %in% \"price\"]  # Exclude price-price correlation\nsorted_correlations <- sort(price_correlations, decreasing = TRUE)\nprint(sorted_correlations)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>       enginesize       horsepower       curbweight         carwidth \n#>       0.88970342       0.84009827       0.83408139       0.74301316 \n#>        carlength        wheelbase        boreratio        carheight \n#>       0.67307358       0.55547499       0.55406923       0.07452058 \n#>           stroke          peakrpm compressionratio       highwaympg \n#>       0.03082326      -0.02085359      -0.17646152      -0.74079733 \n#>          citympg \n#>      -0.74198802\n```\n:::\n\n```{.r .cell-code}\n# Select variables with higher correlations\nthreshold <- 0.5 # Adjustable threshold\nrelevant_variables <- names(sorted_correlations[abs(sorted_correlations) > threshold])\n\n# Filter the dataframe to include only relevant variables\ndf_relevant <- df[, c(\"price\", relevant_variables)]\n\n# Run linear regression using only the relevant variables\nmodel_relevant <- lm(price ~ ., data = df_relevant)\n\n# Summary of the linear regression model\nsummary(model_relevant)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = price ~ ., data = df_relevant)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -8563.4 -1773.4   132.3  1380.1 14109.6 \n#> \n#> Coefficients:\n#>               Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept) -3.458e+04  1.454e+04  -2.379 0.018465 *  \n#> enginesize   1.007e+02  1.437e+01   7.006 5.39e-11 ***\n#> horsepower   6.007e+01  1.605e+01   3.742 0.000249 ***\n#> curbweight   8.124e-01  1.921e+00   0.423 0.672929    \n#> carwidth     2.570e+02  2.643e+02   0.973 0.332144    \n#> carlength   -1.305e+01  6.168e+01  -0.212 0.832732    \n#> wheelbase    1.307e+02  1.050e+02   1.245 0.214707    \n#> boreratio   -6.281e+02  1.260e+03  -0.499 0.618676    \n#> highwaympg   1.118e+02  1.989e+02   0.562 0.574900    \n#> citympg     -9.808e+01  2.140e+02  -0.458 0.647393    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 3414 on 171 degrees of freedom\n#> Multiple R-squared:  0.8299,\tAdjusted R-squared:  0.821 \n#> F-statistic: 92.73 on 9 and 171 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n\n\n# Assignment 4\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-4_5a4f46cd78d949c26f95e646b4f32089'}\n\n```{.r .cell-code}\n# Perform linear regression between price and enginesize\nmodel_enginesize <- lm(price ~ enginesize, data = df)\n\n# Create scatter plot of price vs enginesize with regression line\nggplot(df, aes(x = enginesize, y = price)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE, color = \"red\") +\n  labs(x = \"Engine size\", y = \"Price\") +\n  ggtitle(\"Linear Regression: Price vs Engine size\")\n```\n\n::: {.cell-output-display}\n![](03_regression_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(model_enginesize)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = price ~ enginesize, data = df)\n#> \n#> Residuals:\n#>      Min       1Q   Median       3Q      Max \n#> -10818.6  -1969.6   -168.6   1494.0  14393.9 \n#> \n#> Coefficients:\n#>              Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept) -8622.296    873.535  -9.871   <2e-16 ***\n#> enginesize    170.064      6.523  26.073   <2e-16 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 3694 on 179 degrees of freedom\n#> Multiple R-squared:  0.7916,\tAdjusted R-squared:  0.7904 \n#> F-statistic: 679.8 on 1 and 179 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThe engine size is a continuous numeric variable that takes values between 61 an 326.\nThere is a linear relation with the price. An increase of the engine size leads to an increase in price.\nWith Multiple R-squared 0.7916, adjusted R-squared 0.7904 and  p-value < 2.2e-16, this relation is statistically relevant.\n\n# Assignment 5\n\n::: {.cell hash='03_regression_cache/html/unnamed-chunk-5_7b754677fcb361a6ec8f0af955d32065'}\n\n```{.r .cell-code}\n# Add 'seat_heating' variable with value TRUE for all observations\ndf_with_seat_heating <- df %>%\n  mutate(seat_heating = 1)\n\n# Run linear regression with the added 'seat_heating' variable\nmodel_with_seat_heating <- lm(price ~ ., data = df_with_seat_heating)\n\n# Summary of the linear regression model\nsummary(model_with_seat_heating)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = price ~ ., data = df_with_seat_heating)\n#> \n#> Residuals:\n#>    Min     1Q Median     3Q    Max \n#>  -5662  -1120      0    798   9040 \n#> \n#> Coefficients: (1 not defined because of singularities)\n#>                        Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)          -36269.965  15460.866  -2.346 0.020354 *  \n#> aspirationturbo        1846.206   1041.391   1.773 0.078386 .  \n#> doornumbertwo           242.523    571.929   0.424 0.672172    \n#> carbodyhardtop        -3691.743   1424.825  -2.591 0.010561 *  \n#> carbodyhatchback      -3344.335   1238.359  -2.701 0.007757 ** \n#> carbodysedan          -2292.820   1356.014  -1.691 0.093043 .  \n#> carbodywagon          -3427.921   1490.285  -2.300 0.022885 *  \n#> drivewheelfwd          -504.564   1076.623  -0.469 0.640030    \n#> drivewheelrwd           -15.446   1268.070  -0.012 0.990299    \n#> enginelocationrear     6643.492   2572.275   2.583 0.010806 *  \n#> wheelbase               -30.197     92.776  -0.325 0.745294    \n#> carlength               -29.740     51.672  -0.576 0.565824    \n#> carwidth                731.819    244.533   2.993 0.003258 ** \n#> carheight               123.195    134.607   0.915 0.361617    \n#> curbweight                2.612      1.781   1.467 0.144706    \n#> enginetypedohcv       -8541.957   4749.685  -1.798 0.074219 .  \n#> enginetypel             978.748   1786.384   0.548 0.584619    \n#> enginetypeohc          3345.252    933.001   3.585 0.000461 ***\n#> enginetypeohcf          972.919   1625.631   0.598 0.550462    \n#> enginetypeohcv        -6222.322   1236.415  -5.033 1.43e-06 ***\n#> cylindernumberfive   -11724.540   3019.192  -3.883 0.000157 ***\n#> cylindernumberfour   -11549.326   3177.177  -3.635 0.000387 ***\n#> cylindernumbersix     -7151.398   2247.230  -3.182 0.001793 ** \n#> cylindernumberthree   -4318.929   4688.833  -0.921 0.358545    \n#> cylindernumbertwelve -11122.209   4196.494  -2.650 0.008946 ** \n#> enginesize              125.934     26.541   4.745 5.00e-06 ***\n#> fuelsystem2bbl          177.136    883.615   0.200 0.841400    \n#> fuelsystemmfi         -3041.018   2576.996  -1.180 0.239934    \n#> fuelsystemmpfi          359.278   1001.529   0.359 0.720326    \n#> fuelsystemspdi        -2543.890   1363.546  -1.866 0.064140 .  \n#> fuelsystemspfi          514.766   2499.229   0.206 0.837107    \n#> boreratio             -1306.740   1642.221  -0.796 0.427516    \n#> stroke                -4527.137    922.732  -4.906 2.49e-06 ***\n#> compressionratio       -737.901    555.960  -1.327 0.186539    \n#> horsepower               10.293     22.709   0.453 0.651035    \n#> peakrpm                   2.526      0.634   3.983 0.000108 ***\n#> citympg                 -90.352    166.647  -0.542 0.588538    \n#> highwaympg              154.858    167.148   0.926 0.355761    \n#> seat_heating                 NA         NA      NA       NA    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2189 on 143 degrees of freedom\n#> Multiple R-squared:  0.9415,\tAdjusted R-squared:  0.9264 \n#> F-statistic: 62.21 on 37 and 143 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThe result NA (Not Applicable) points to the fact that there is no change whatsoever in seat heating, therefore its changes cannot be related to the changes in price.\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}